In [0]:
!pip install numpy

You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [0]:
import numpy as np

In [0]:
data1 = list(range(1,100))

In [0]:
type(data1)

list

In [0]:
arr1 = np.array(data1)

In [0]:
type(arr1)

numpy.ndarray

In [0]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [0]:
arr1.tolist()

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [0]:
# properties of the array

In [0]:
arr1.dtype

dtype('int64')

In [0]:
arr1.ndim

1

In [0]:
arr1.shape

(99,)

In [0]:
arr1.size

99

In [0]:
len(arr1)

99

In [0]:
# special arrays

In [0]:
np.zeros(2)

array([ 0.,  0.])

In [0]:
np.zeros((3,6))

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [0]:
np.ones(2)

array([ 1.,  1.])

In [0]:
np.ones((3,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [0]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [0]:
A = np.array([[12,23,34],[21,34,54],[45,65,67]])

In [0]:
A

array([[12, 23, 34],
       [21, 34, 54],
       [45, 65, 67]])

In [0]:
B = np.array([12,32,np.zeros(1)])

In [0]:
B

array([ 12.,  32.,   0.])

In [0]:
np.dot(A,B)

array([  880.,  1340.,  2620.])

In [0]:
(12*12)+(23*32)

880

In [0]:
np.linspace(0.11,0.99,20)

array([ 0.11      ,  0.15631579,  0.20263158,  0.24894737,  0.29526316,
        0.34157895,  0.38789474,  0.43421053,  0.48052632,  0.52684211,
        0.57315789,  0.61947368,  0.66578947,  0.71210526,  0.75842105,
        0.80473684,  0.85105263,  0.89736842,  0.94368421,  0.99      ])

In [0]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

In [0]:
A

array([[12, 23, 34],
       [21, 34, 54],
       [45, 65, 67]])

In [0]:
A = np.array([[12, 23, 34],
       [21, 34, 54],
       [45, 65, 67],
             [56,67,78],
             [78,89,90]])

In [0]:
A

array([[12, 23, 34],
       [21, 34, 54],
       [45, 65, 67],
       [56, 67, 78],
       [78, 89, 90]])

In [0]:
A.flatten()

array([12, 23, 34, 21, 34, 54, 45, 65, 67, 56, 67, 78, 78, 89, 90])

In [0]:
A.shape

(5, 3)

In [0]:
c = np.array([[12, 23, 34, 21, 34, 54, 45, 65, 67, 56, 67, 78, 78, 89, 90]])

In [0]:
c

array([[12, 23, 34, 21, 34, 54, 45, 65, 67, 56, 67, 78, 78, 89, 90]])

In [0]:
c.ndim

2

In [0]:
c.shape

(1, 15)

In [0]:
c.flatten()

array([12, 23, 34, 21, 34, 54, 45, 65, 67, 56, 67, 78, 78, 89, 90])

In [0]:
a =A

In [0]:
a

array([[12, 23, 34],
       [21, 34, 54],
       [45, 65, 67],
       [56, 67, 78],
       [78, 89, 90]])

In [0]:
a[0]

array([12, 23, 34])

In [0]:
a[2]

array([45, 65, 67])

In [0]:
a[0,2]

34

In [0]:
a[2,1]

65

In [0]:
a[0:2,:]

array([[12, 23, 34],
       [21, 34, 54]])

In [0]:
a[:2,0:]

array([[12, 23, 34],
       [21, 34, 54]])

In [0]:
a[1][2]

54

In [0]:
a

array([[12, 23, 34],
       [21, 34, 54],
       [45, 65, 67],
       [56, 67, 78],
       [78, 89, 90]])

In [0]:
np.sqrt(a)

array([[ 3.46410162,  4.79583152,  5.83095189],
       [ 4.58257569,  5.83095189,  7.34846923],
       [ 6.70820393,  8.06225775,  8.18535277],
       [ 7.48331477,  8.18535277,  8.83176087],
       [ 8.83176087,  9.43398113,  9.48683298]])

In [0]:
np.ceil(np.sqrt(a))

array([[  4.,   5.,   6.],
       [  5.,   6.,   8.],
       [  7.,   9.,   9.],
       [  8.,   9.,   9.],
       [  9.,  10.,  10.]])

In [0]:
np.floor(np.sqrt(a))

array([[ 3.,  4.,  5.],
       [ 4.,  5.,  7.],
       [ 6.,  8.,  8.],
       [ 7.,  8.,  8.],
       [ 8.,  9.,  9.]])

In [0]:
np.mean(a)

54.200000000000003

In [0]:
np.std(a)

24.263003386500468

In [0]:
a

array([[12, 23, 34],
       [21, 34, 54],
       [45, 65, 67],
       [56, 67, 78],
       [78, 89, 90]])

In [0]:
a.argmax()

14

In [0]:
a.shape

(5, 3)

In [0]:
a[4][2]

90

In [0]:
a.flatten()[a.argmax()]

90

In [0]:
a.flatten()[a.argmin()]

12

In [0]:
np.where(a > 50,99,999).all()

True

In [0]:
a[a>50]

array([54, 65, 67, 56, 67, 78, 78, 89, 90])

In [0]:
a

array([[12, 23, 34],
       [21, 34, 54],
       [45, 65, 67],
       [56, 67, 78],
       [78, 89, 90]])

In [0]:
a.shape

(5, 3)

In [0]:
a.T

array([[12, 21, 45, 56, 78],
       [23, 34, 65, 67, 89],
       [34, 54, 67, 78, 90]])

In [0]:
a.flatten().shape

(15,)

In [0]:
add_rows = np.array(np.zeros(17))

In [0]:
f = add_rows.tolist()

In [0]:
a.flatten()

array([12, 23, 34, 21, 34, 54, 45, 65, 67, 56, 67, 78, 78, 89, 90])

In [0]:
d = [12, 23, 34, 21, 34, 54, 45, 65, 67, 56, 67, 78, 78, 89, 90]

In [0]:
d.append(np.zeros(17).flatten())

In [0]:
d1 = d + list(np.zeros(17))

In [0]:
np.array(d1).reshape(8,4)

array([[ 12.,  23.,  34.,  21.],
       [ 34.,  54.,  45.,  65.],
       [ 67.,  56.,  67.,  78.],
       [ 78.,  89.,  90.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.]])