In [0]:
import numpy as np
a = np.ones(10).reshape(5,2)

In [0]:
a*6

array([[ 6.,  6.],
       [ 6.,  6.],
       [ 6.,  6.],
       [ 6.,  6.],
       [ 6.,  6.]])

In [0]:
a[2] = [21.0,32.1]

In [0]:
a

array([[  1. ,   1. ],
       [  1. ,   1. ],
       [ 21. ,  32.1],
       [  1. ,   1. ],
       [  1. ,   1. ]])

In [0]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

In [0]:
a.flags.writeable = False

In [0]:
a

array([[  1. ,   1. ],
       [  1. ,   1. ],
       [ 21. ,  32.1],
       [  1. ,   1. ],
       [  1. ,   1. ]])

In [0]:
a[2] = [1.0,1.0]

ValueError: assignment destination is read-only

In [0]:
a[3:]

array([[ 1.,  1.],
       [ 1.,  1.]])

In [0]:
a.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  UPDATEIFCOPY : False

In [0]:
np.corrcoef([21,34,54],[32,43,54])

array([[ 1.        ,  0.99258408],
       [ 0.99258408,  1.        ]])

In [0]:
# Import the library
import pandas as pd
# other necessary library
import numpy as np
import os
import matplotlib.pyplot as plt
%matplotlib inline

In [0]:
!pip3 install pandas

In [0]:
# To check the version:
pd.__version__

'0.20.3'

In [0]:
## To get current working directory
%pwd

'/Users/pradmishra/Documents/Python Trainings '

In [0]:
# read a file from eternal sources

In [0]:
# csv
# tsv
# excel
# SPSS
# SAS
# SQL
# HDFS
# txt
# JSON

In [0]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=False, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, skip_footer=0, doublequote=True, delim_whitespace=False, as_recarray=False, compact_ints=False, use_unsigned=False, low_memory=True, buffer_lines=None, memory_map=False, float_precision=No

In [0]:
diamonds = pd.read_csv('https://raw.githubusercontent.com/tidyverse/ggplot2/master/data-raw/diamonds.csv')

In [0]:
diamonds.head(10) #data frame

carat        cut color clarity  depth  table  price     x     y     z
0   0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
5   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7   0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
8   0.22       Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
9   0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39

In [0]:
diamonds.tail(3)

carat        cut color clarity  depth  table  price     x     y     z
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [0]:
help(pd.read_csv)

Help on function read_csv in module pandas.io.parsers:

read_csv(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=False, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, skip_footer=0, doublequote=True, delim_whitespace=False, as_recarray=False, compact_ints=False, use_unsigned=False, low_memory=True, buffer_lines=None, memory_map=False, float_precision=No

In [0]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv',
                 sep=';')

In [0]:
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [0]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',header=None)

In [0]:
df.head()

0                  1       2           3   4                    5   \
0  39          State-gov   77516   Bachelors  13        Never-married   
1  50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2  38            Private  215646     HS-grad   9             Divorced   
3  53            Private  234721        11th   7   Married-civ-spouse   
4  28            Private  338409   Bachelors  13   Married-civ-spouse   

                   6               7       8        9     10  11  12  \
0        Adm-clerical   Not-in-family   White     Male  2174   0  40   
1     Exec-managerial         Husband   White     Male     0   0  13   
2   Handlers-cleaners   Not-in-family   White     Male     0   0  40   
3   Handlers-cleaners         Husband   Black     Male     0   0  40   
4      Prof-specialty            Wife   Black   Female     0   0  40   

               13      14  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [0]:
df.columns = ['col1','col2','col3','col4','','','','','','','','col12','col13','col14','col15' ]

In [0]:
df.head()

col1               col2    col3        col4                           \
0    39          State-gov   77516   Bachelors  13        Never-married   
1    50   Self-emp-not-inc   83311   Bachelors  13   Married-civ-spouse   
2    38            Private  215646     HS-grad   9             Divorced   
3    53            Private  234721        11th   7   Married-civ-spouse   
4    28            Private  338409   Bachelors  13   Married-civ-spouse   

                                                              col12  col13  \
0        Adm-clerical   Not-in-family   White     Male  2174      0     40   
1     Exec-managerial         Husband   White     Male     0      0     13   
2   Handlers-cleaners   Not-in-family   White     Male     0      0     40   
3   Handlers-cleaners         Husband   Black     Male     0      0     40   
4      Prof-specialty            Wife   Black   Female     0      0     40   

            col14   col15  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3   United-States   <=50K  
4            Cuba   <=50K

In [0]:
df.shape

(32561, 15)

In [0]:
# diamonds

In [0]:
diamonds.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [0]:
diamonds.head(3)

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31

In [0]:
diamonds.tail(3)

carat        cut color clarity  depth  table  price     x     y     z
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

In [0]:
diamonds.columns = ['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x_other', 'y_other','z_other']

In [0]:
diamonds.head()

carat      cut color clarity  depth  table  price  x_other  y_other  \
0   0.23    Ideal     E     SI2   61.5   55.0    326     3.95     3.98   
1   0.21  Premium     E     SI1   59.8   61.0    326     3.89     3.84   
2   0.23     Good     E     VS1   56.9   65.0    327     4.05     4.07   
3   0.29  Premium     I     VS2   62.4   58.0    334     4.20     4.23   
4   0.31     Good     J     SI2   63.3   58.0    335     4.34     4.35   

   z_other  
0     2.43  
1     2.31  
2     2.31  
3     2.63  
4     2.75

In [0]:
diamonds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
carat      53940 non-null float64
cut        53940 non-null object
color      53940 non-null object
clarity    53940 non-null object
depth      53940 non-null float64
table      53940 non-null float64
price      53940 non-null int64
x_other    53940 non-null float64
y_other    53940 non-null float64
z_other    53940 non-null float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB


In [0]:
diamonds.dtypes

carat      float64
cut         object
color       object
clarity     object
depth      float64
table      float64
price        int64
x_other    float64
y_other    float64
z_other    float64
dtype: object

In [0]:
diamonds.head()

carat      cut color clarity  depth  table  price  x_other  y_other  \
0   0.23    Ideal     E     SI2   61.5   55.0    326     3.95     3.98   
1   0.21  Premium     E     SI1   59.8   61.0    326     3.89     3.84   
2   0.23     Good     E     VS1   56.9   65.0    327     4.05     4.07   
3   0.29  Premium     I     VS2   62.4   58.0    334     4.20     4.23   
4   0.31     Good     J     SI2   63.3   58.0    335     4.34     4.35   

   z_other  
0     2.43  
1     2.31  
2     2.31  
3     2.63  
4     2.75

In [0]:
type(diamonds.carat)

pandas.core.series.Series

In [0]:
type(diamonds.color)

pandas.core.series.Series

In [0]:
type(diamonds)

pandas.core.frame.DataFrame

In [0]:
# two different ways of accesing the columns

In [0]:
diamonds.cut[0:10]

0        Ideal
1      Premium
2         Good
3      Premium
4         Good
5    Very Good
6    Very Good
7    Very Good
8         Fair
9    Very Good
Name: cut, dtype: object

In [0]:
diamonds['cut'][0:10]

0        Ideal
1      Premium
2         Good
3      Premium
4         Good
5    Very Good
6    Very Good
7    Very Good
8         Fair
9    Very Good
Name: cut, dtype: object

In [0]:
# distinct values in a data column

In [0]:
set(diamonds.cut)

{'Fair', 'Good', 'Ideal', 'Premium', 'Very Good'}

In [0]:
set(diamonds.color)

{'D', 'E', 'F', 'G', 'H', 'I', 'J'}

In [0]:
set(diamonds.clarity)

{'I1', 'IF', 'SI1', 'SI2', 'VS1', 'VS2', 'VVS1', 'VVS2'}

In [0]:
diamonds.shape #rows and columns

(53940, 10)

In [0]:
diamonds.cut.value_counts()

Ideal        21551
Premium      13791
Very Good    12082
Good          4906
Fair          1610
Name: cut, dtype: int64

In [0]:
diamonds.color.value_counts()

G    11292
E     9797
F     9542
H     8304
D     6775
I     5422
J     2808
Name: color, dtype: int64

In [0]:
diamonds.clarity.value_counts()

SI1     13065
VS2     12258
SI2      9194
VS1      8171
VVS2     5066
VVS1     3655
IF       1790
I1        741
Name: clarity, dtype: int64

In [0]:
diamonds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
carat      53940 non-null float64
cut        53940 non-null object
color      53940 non-null object
clarity    53940 non-null object
depth      53940 non-null float64
table      53940 non-null float64
price      53940 non-null int64
x_other    53940 non-null float64
y_other    53940 non-null float64
z_other    53940 non-null float64
dtypes: float64(6), int64(1), object(3)
memory usage: 4.1+ MB


In [0]:
diamonds.describe()

carat         depth         table         price       x_other  \
count  53940.000000  53940.000000  53940.000000  53940.000000  53940.000000   
mean       0.797940     61.749405     57.457184   3932.799722      5.731157   
std        0.474011      1.432621      2.234491   3989.439738      1.121761   
min        0.200000     43.000000     43.000000    326.000000      0.000000   
25%        0.400000     61.000000     56.000000    950.000000      4.710000   
50%        0.700000     61.800000     57.000000   2401.000000      5.700000   
75%        1.040000     62.500000     59.000000   5324.250000      6.540000   
max        5.010000     79.000000     95.000000  18823.000000     10.740000   

            y_other       z_other  
count  53940.000000  53940.000000  
mean       5.734526      3.538734  
std        1.142135      0.705699  
min        0.000000      0.000000  
25%        4.720000      2.910000  
50%        5.710000      3.530000  
75%        6.540000      4.040000  
max       58.900000     31.800000

In [0]:
diamonds.describe(include=['object'])

cut  color clarity
count   53940  53940   53940
unique      5      7       8
top     Ideal      G     SI1
freq    21551  11292   13065

In [0]:
# how to select columns

In [0]:
diamonds.head()


carat      cut color clarity  depth  table  price  x_other  y_other  \
0   0.23    Ideal     E     SI2   61.5   55.0    326     3.95     3.98   
1   0.21  Premium     E     SI1   59.8   61.0    326     3.89     3.84   
2   0.23     Good     E     VS1   56.9   65.0    327     4.05     4.07   
3   0.29  Premium     I     VS2   62.4   58.0    334     4.20     4.23   
4   0.31     Good     J     SI2   63.3   58.0    335     4.34     4.35   

   z_other  
0     2.43  
1     2.31  
2     2.31  
3     2.63  
4     2.75

In [0]:
my_cols = ['x_other','y_other','z_other']

In [0]:
diamonds[my_cols].head()

x_other  y_other  z_other
0     3.95     3.98     2.43
1     3.89     3.84     2.31
2     4.05     4.07     2.31
3     4.20     4.23     2.63
4     4.34     4.35     2.75

In [0]:
diamonds[['x_other','y_other','z_other']].head()


x_other  y_other  z_other
0     3.95     3.98     2.43
1     3.89     3.84     2.31
2     4.05     4.07     2.31
3     4.20     4.23     2.63
4     4.34     4.35     2.75

In [0]:
# two kinds of filtering in dataframes

In [0]:
# simple logical filtering
diamonds[(diamonds.carat > 3.5)].head() 

carat        cut color clarity  depth  table  price  x_other  y_other  \
23644   3.65       Fair     H      I1   67.1   53.0  11668     9.53     9.48   
25998   4.01    Premium     I      I1   61.0   61.0  15223    10.14    10.10   
25999   4.01    Premium     J      I1   62.5   62.0  15223    10.02     9.94   
26444   4.00  Very Good     I      I1   63.3   58.0  15984    10.01     9.94   
26534   3.67    Premium     I      I1   62.4   56.0  16193     9.86     9.81   

       z_other  
23644     6.38  
25998     6.17  
25999     6.24  
26444     6.31  
26534     6.13

In [0]:
#advanced filtering
diamonds[(diamonds.carat > 3.5) | (diamonds.price > 12000)].head() #or condition

carat        cut color clarity  depth  table  price  x_other  y_other  \
23644   3.65       Fair     H      I1   67.1   53.0  11668     9.53     9.48   
23897   1.57      Ideal     H     VS2   61.8   55.0  12004     7.45     7.49   
23898   1.50  Very Good     G     VS1   63.4   59.0  12005     7.25     7.19   
23899   1.31      Ideal     G     VS1   61.6   57.0  12008     6.99     7.04   
23900   1.50      Ideal     G     SI1   61.0   57.0  12009     7.38     7.41   

       z_other  
23644     6.38  
23897     4.62  
23898     4.58  
23899     4.32  
23900     4.51

In [0]:
diamonds[(diamonds.carat > 3.5) & (diamonds.price > 12000)].head() #and condition

carat        cut color clarity  depth  table  price  x_other  y_other  \
25998   4.01    Premium     I      I1   61.0   61.0  15223    10.14    10.10   
25999   4.01    Premium     J      I1   62.5   62.0  15223    10.02     9.94   
26444   4.00  Very Good     I      I1   63.3   58.0  15984    10.01     9.94   
26534   3.67    Premium     I      I1   62.4   56.0  16193     9.86     9.81   
27130   4.13       Fair     H      I1   64.8   61.0  17329    10.00     9.85   

       z_other  
25998     6.17  
25999     6.24  
26444     6.31  
26534     6.13  
27130     6.43

In [0]:
diamonds[(diamonds.carat > 3.5) & (diamonds.price > 12000)]['cut']

25998      Premium
25999      Premium
26444    Very Good
26534      Premium
27130         Fair
27415         Fair
27630         Fair
27679      Premium
Name: cut, dtype: object

In [0]:
diamonds[(diamonds.carat > 3.5) & (diamonds.price > 12000)][['cut','clarity','color']]

cut clarity color
25998    Premium      I1     I
25999    Premium      I1     J
26444  Very Good      I1     I
26534    Premium      I1     I
27130       Fair      I1     H
27415       Fair      I1     J
27630       Fair      I1     J
27679    Premium     VS2     J

In [0]:
diamonds[diamonds.cut.isin(['Good','Premium'])].head(10)

carat      cut color clarity  depth  table  price  x_other  y_other  \
1    0.21  Premium     E     SI1   59.8   61.0    326     3.89     3.84   
2    0.23     Good     E     VS1   56.9   65.0    327     4.05     4.07   
3    0.29  Premium     I     VS2   62.4   58.0    334     4.20     4.23   
4    0.31     Good     J     SI2   63.3   58.0    335     4.34     4.35   
10   0.30     Good     J     SI1   64.0   55.0    339     4.25     4.28   
12   0.22  Premium     F     SI1   60.4   61.0    342     3.88     3.84   
14   0.20  Premium     E     SI2   60.2   62.0    345     3.79     3.75   
15   0.32  Premium     E      I1   60.9   58.0    345     4.38     4.42   
17   0.30     Good     J     SI1   63.4   54.0    351     4.23     4.29   
18   0.30     Good     J     SI1   63.8   56.0    351     4.23     4.26   

    z_other  
1      2.31  
2      2.31  
3      2.63  
4      2.75  
10     2.73  
12     2.33  
14     2.27  
15     2.68  
17     2.70  
18     2.71

In [0]:
diamonds[diamonds.color.isin(['G','D'])].head(10)

carat        cut color clarity  depth  table  price  x_other  y_other  \
25   0.23  Very Good     G    VVS2   60.4   58.0    354     3.97     4.01   
28   0.23  Very Good     D     VS2   60.5   61.0    357     3.96     3.97   
34   0.23  Very Good     D     VS1   61.9   58.0    402     3.92     3.96   
38   0.26  Very Good     D     VS2   60.8   59.0    403     4.13     4.16   
42   0.26       Good     D     VS2   65.2   56.0    403     3.99     4.02   
43   0.26       Good     D     VS1   58.4   63.0    403     4.19     4.24   
51   0.23      Ideal     G     VS1   61.9   54.0    404     3.93     3.95   
54   0.22    Premium     D     VS2   59.3   62.0    404     3.91     3.88   
61   0.30    Premium     D     SI1   62.6   59.0    552     4.23     4.27   
62   0.30      Ideal     D     SI1   62.5   57.0    552     4.29     4.32   

    z_other  
25     2.41  
28     2.40  
34     2.44  
38     2.52  
42     2.61  
43     2.46  
51     2.44  
54     2.31  
61     2.66  
62     2.69

In [0]:
df1 = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',
                 sep='\t')

In [0]:
df1.head()

order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa   
1         1         1                                   Izze   
2         1         1                       Nantucket Nectar   
3         1         1  Chips and Tomatillo-Green Chili Salsa   
4         2         2                           Chicken Bowl   

                                  choice_description item_price  
0                                                NaN     $2.39   
1                                       [Clementine]     $3.39   
2                                            [Apple]     $3.39   
3                                                NaN     $2.39   
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98

In [0]:
diamonds.index

RangeIndex(start=0, stop=53940, step=1)