In [0]:
import numpy as np

In [0]:
mat = [[12,23,34,45,56,67,78,],[21,32,43,54,65,76,87],[32,45,65,76,78,87,89]]

In [0]:
mat

[[12, 23, 34, 45, 56, 67, 78],
 [21, 32, 43, 54, 65, 76, 87],
 [32, 45, 65, 76, 78, 87, 89]]

In [0]:
arr2 = np.array(mat)

In [0]:
tup1 = [(12,23,34,45,56,67,78),(21,32,43,54,65,76,87),(32,45,65,76,78,87,89)]

In [0]:
tup1

[(12, 23, 34, 45, 56, 67, 78),
 (21, 32, 43, 54, 65, 76, 87),
 (32, 45, 65, 76, 78, 87, 89)]

In [0]:
type(tup1)

list

In [0]:
arr1 = np.array(tup1)

In [0]:
arr1+arr2

array([[ 24,  46,  68,  90, 112, 134, 156],
       [ 42,  64,  86, 108, 130, 152, 174],
       [ 64,  90, 130, 152, 156, 174, 178]])

In [0]:
arr1*arr2

array([[ 144,  529, 1156, 2025, 3136, 4489, 6084],
       [ 441, 1024, 1849, 2916, 4225, 5776, 7569],
       [1024, 2025, 4225, 5776, 6084, 7569, 7921]])

In [0]:
arr1/arr2

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [0]:
arr1-arr2

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [0]:
arr1*1000

array([[12000, 23000, 34000, 45000, 56000, 67000, 78000],
       [21000, 32000, 43000, 54000, 65000, 76000, 87000],
       [32000, 45000, 65000, 76000, 78000, 87000, 89000]])

In [0]:
arr1**2

array([[ 144,  529, 1156, 2025, 3136, 4489, 6084],
       [ 441, 1024, 1849, 2916, 4225, 5776, 7569],
       [1024, 2025, 4225, 5776, 6084, 7569, 7921]])

In [0]:
arr1**3

array([[  1728,  12167,  39304,  91125, 175616, 300763, 474552],
       [  9261,  32768,  79507, 157464, 274625, 438976, 658503],
       [ 32768,  91125, 274625, 438976, 474552, 658503, 704969]])

In [0]:
pow(arr1,0.5)

array([[ 3.46410162,  4.79583152,  5.83095189,  6.70820393,  7.48331477,
         8.18535277,  8.83176087],
       [ 4.58257569,  5.65685425,  6.55743852,  7.34846923,  8.06225775,
         8.71779789,  9.32737905],
       [ 5.65685425,  6.70820393,  8.06225775,  8.71779789,  8.83176087,
         9.32737905,  9.43398113]])

In [0]:
np.sqrt(arr1)

array([[ 3.46410162,  4.79583152,  5.83095189,  6.70820393,  7.48331477,
         8.18535277,  8.83176087],
       [ 4.58257569,  5.65685425,  6.55743852,  7.34846923,  8.06225775,
         8.71779789,  9.32737905],
       [ 5.65685425,  6.70820393,  8.06225775,  8.71779789,  8.83176087,
         9.32737905,  9.43398113]])

In [0]:
np.sum(arr1)

1165

In [0]:
np.mean(arr1)

55.476190476190474

In [0]:
np.std(arr1)

23.255555501385139

In [0]:
np.prod(arr1,axis=0)

array([  8064,  33120,  95030, 184680, 283920, 443004, 603954])

In [0]:
np.prod(arr1,axis=1)

array([ 123582775680,  670621835520, 4296287174400])

In [0]:
np.var(arr1)

540.82086167800458

In [0]:
np.median(arr1)

56.0

In [0]:
np.percentile(arr1,5)

21.0

In [0]:
np.dot(arr1,arr2.T)

array([[17563, 20398, 24188],
       [20398, 23800, 28436],
       [24188, 28436, 34624]])

In [0]:
arr1

array([[12, 23, 34, 45, 56, 67, 78],
       [21, 32, 43, 54, 65, 76, 87],
       [32, 45, 65, 76, 78, 87, 89]])

In [0]:
arr2.T

array([[12, 21, 32],
       [23, 32, 45],
       [34, 43, 65],
       [45, 54, 76],
       [56, 65, 78],
       [67, 76, 87],
       [78, 87, 89]])

In [0]:
arr1.shape

(3, 7)

In [0]:
arr2.T.shape

(7, 3)

In [0]:
np.inner(arr1,arr2)

array([[17563, 20398, 24188],
       [20398, 23800, 28436],
       [24188, 28436, 34624]])

In [0]:
np.outer(arr1,arr2)

array([[ 144,  276,  408,  540,  672,  804,  936,  252,  384,  516,  648,
         780,  912, 1044,  384,  540,  780,  912,  936, 1044, 1068],
       [ 276,  529,  782, 1035, 1288, 1541, 1794,  483,  736,  989, 1242,
        1495, 1748, 2001,  736, 1035, 1495, 1748, 1794, 2001, 2047],
       [ 408,  782, 1156, 1530, 1904, 2278, 2652,  714, 1088, 1462, 1836,
        2210, 2584, 2958, 1088, 1530, 2210, 2584, 2652, 2958, 3026],
       [ 540, 1035, 1530, 2025, 2520, 3015, 3510,  945, 1440, 1935, 2430,
        2925, 3420, 3915, 1440, 2025, 2925, 3420, 3510, 3915, 4005],
       [ 672, 1288, 1904, 2520, 3136, 3752, 4368, 1176, 1792, 2408, 3024,
        3640, 4256, 4872, 1792, 2520, 3640, 4256, 4368, 4872, 4984],
       [ 804, 1541, 2278, 3015, 3752, 4489, 5226, 1407, 2144, 2881, 3618,
        4355, 5092, 5829, 2144, 3015, 4355, 5092, 5226, 5829, 5963],
       [ 936, 1794, 2652, 3510, 4368, 5226, 6084, 1638, 2496, 3354, 4212,
        5070, 5928, 6786, 2496, 3510, 5070, 5928, 6084, 6786, 6942],

In [0]:
arr1.T

array([[12, 21, 32],
       [23, 32, 45],
       [34, 43, 65],
       [45, 54, 76],
       [56, 65, 78],
       [67, 76, 87],
       [78, 87, 89]])

In [0]:
np.transpose(arr1)

array([[12, 21, 32],
       [23, 32, 45],
       [34, 43, 65],
       [45, 54, 76],
       [56, 65, 78],
       [67, 76, 87],
       [78, 87, 89]])

In [0]:
arr1.ndim

2

In [0]:
np.sum(np.diag(arr1))

109

In [0]:
np.trace(arr1)

109