In [0]:
import numpy as np

In [0]:
np.sqrt(100)

10.0

In [0]:
# functions in python:
# built in function
# custom function

In [0]:
def sqrtt(x): #example of only args
    return x**0.5

In [0]:
sqrtt(100)

10.0

In [0]:
def happy(**kwargs):
    if kwargs is not None:
        for key, value in kwargs.iteritems():
            print(key,value)

In [0]:
#def happy(**kwargs):
 #   print(kwargs)

In [0]:
d3 = {'name': 'john'
       }

In [0]:
d3.items()

dict_items([('name', 'john')])

In [0]:
happy(**d3)

AttributeError: 'dict' object has no attribute 'iteritems'

In [0]:
def arguments(arg1,arg2,arg3):
    print(arg1)
    print(arg2)
    print(arg3)

In [0]:
args = ('my',33,'cents') #it does not require a dict object

In [0]:
arguments(*args)

my
33
cents


In [0]:
kwargs = {'arg1':'my','arg2':33,'arg3':'cents'} # a dict

In [0]:
arguments(**kwargs)

my
33
cents


In [0]:
def square(a,b,c):
    print(a**b**c)

In [0]:
args = (2,3,4)

In [0]:
square(*args) #args

2417851639229258349412352


In [0]:
dict1 = {'a':2,'b':3,'c':4}

In [0]:
square(**dict1) #kwargs

2417851639229258349412352


In [0]:
# Adjusted R square

# R -square

In [0]:
# distributions

# feature creation

# testing of features

In [0]:
# stat models are not always optimized

# ML models are always optimized

In [0]:
import numpy as np

In [0]:
d = [21,23,34,45,56,67,78,89]

In [0]:
type(d)

list

In [0]:
np.array(d)

array([21, 23, 34, 45, 56, 67, 78, 89])

In [0]:
A = np.array([[3,-2,1],[2,3,-5],[-5,-7,3]])

B = np.array([14,25,28])

In [0]:
A

array([[ 3, -2,  1],
       [ 2,  3, -5],
       [-5, -7,  3]])

In [0]:
B

array([14, 25, 28])

In [0]:
np.linalg.solve(A,B)

array([  1.67826087,  -9.49565217, -10.02608696])

In [0]:
np.linalg.det(A)

-115.00000000000001

In [0]:
np.array([[2, 5.4, 1], [3.1, 5, 4]])

array([[ 2. ,  5.4,  1. ],
       [ 3.1,  5. ,  4. ]])

In [0]:
np.array([[2, 5.4, '?'], [3.1, 5, 4]])

array([['2', '5.4', '?'],
       ['3.1', '5', '4']], 
      dtype='<U32')

In [0]:
np.array([[2, 5.4, True], [3.1, 5, 4]])

array([[ 2. ,  5.4,  1. ],
       [ 3.1,  5. ,  4. ]])

In [0]:
np.array([[2, 5.4, None], [3.1, 5, 4]])

array([[2, 5.4, None],
       [3.1, 5, 4]], dtype=object)

In [0]:
# string > float > integer

In [0]:
d1 = np.array([[2, 5.4, '?'], [3.1, 5, 4]])

In [0]:
d1.ndim

2

In [0]:
d1.size

6

In [0]:
d1.shape

(2, 3)

In [0]:
d1.dtype

dtype('<U32')

In [0]:
A

array([[ 3, -2,  1],
       [ 2,  3, -5],
       [-5, -7,  3]])

In [0]:
w,v = np.linalg.eig(A)

In [0]:
w #eigen values

array([ 6.02413385+1.19839754j,  6.02413385-1.19839754j, -3.04826770+0.j        ])

In [0]:
v #eigen vectors

array([[ 0.51763744-0.18115428j,  0.51763744+0.18115428j,  0.07602323+0.j        ],
       [-0.60481749+0.j        , -0.60481749-0.j        ,  0.62025727+0.j        ],
       [ 0.57286479+0.07250065j,  0.57286479-0.07250065j,  0.78070570+0.j        ]])

In [0]:
d1 = [6,7,8,9,12,23]

In [0]:
d1

[6, 7, 8, 9, 12, 23]

In [0]:
np.asarray(d1)

array([ 6,  7,  8,  9, 12, 23])

In [0]:
np.array(d1)

array([ 6,  7,  8,  9, 12, 23])

In [0]:
d2 = [list(range(1,10)),list(range(10,20))]

In [0]:
d2

[[1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]

In [0]:
np.asarray(d2)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]], dtype=object)

In [0]:
np.array(d2)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]], dtype=object)

In [0]:
d3 = np.array(d2)

In [0]:
d3

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]], dtype=object)

In [0]:
d3.tolist()

[[1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]

In [0]:
d2

[[1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]

In [0]:
d3

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]], dtype=object)

In [0]:
d3.dtype

dtype('O')

In [0]:
d3.ndim

1

In [0]:
d3.shape

(2,)

In [0]:
d3.size

2

In [0]:
len(d3)

2

In [0]:
#special arrays as helper functions

In [0]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [0]:
np.zeros((10,10))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [0]:
np.ones((10,10))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [0]:
np.linspace(0,100,50)

array([   0.        ,    2.04081633,    4.08163265,    6.12244898,
          8.16326531,   10.20408163,   12.24489796,   14.28571429,
         16.32653061,   18.36734694,   20.40816327,   22.44897959,
         24.48979592,   26.53061224,   28.57142857,   30.6122449 ,
         32.65306122,   34.69387755,   36.73469388,   38.7755102 ,
         40.81632653,   42.85714286,   44.89795918,   46.93877551,
         48.97959184,   51.02040816,   53.06122449,   55.10204082,
         57.14285714,   59.18367347,   61.2244898 ,   63.26530612,
         65.30612245,   67.34693878,   69.3877551 ,   71.42857143,
         73.46938776,   75.51020408,   77.55102041,   79.59183673,
         81.63265306,   83.67346939,   85.71428571,   87.75510204,
         89.79591837,   91.83673469,   93.87755102,   95.91836735,
         97.95918367,  100.        ])

In [0]:
np.eye(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [0]:
np.array([[2, 5.4, 1], [3.1, 5, 4]])

array([[ 2. ,  5.4,  1. ],
       [ 3.1,  5. ,  4. ]])

In [0]:
np.linspace(10,100,20)

array([  10.        ,   14.73684211,   19.47368421,   24.21052632,
         28.94736842,   33.68421053,   38.42105263,   43.15789474,
         47.89473684,   52.63157895,   57.36842105,   62.10526316,
         66.84210526,   71.57894737,   76.31578947,   81.05263158,
         85.78947368,   90.52631579,   95.26315789,  100.        ])

In [0]:
np.linspace(10,100,20)

array([  10.        ,   14.73684211,   19.47368421,   24.21052632,
         28.94736842,   33.68421053,   38.42105263,   43.15789474,
         47.89473684,   52.63157895,   57.36842105,   62.10526316,
         66.84210526,   71.57894737,   76.31578947,   81.05263158,
         85.78947368,   90.52631579,   95.26315789,  100.        ])

In [0]:
np.linspace(10,100,20)

array([  10.        ,   14.73684211,   19.47368421,   24.21052632,
         28.94736842,   33.68421053,   38.42105263,   43.15789474,
         47.89473684,   52.63157895,   57.36842105,   62.10526316,
         66.84210526,   71.57894737,   76.31578947,   81.05263158,
         85.78947368,   90.52631579,   95.26315789,  100.        ])

In [0]:
(100-10)/20

4.5

In [0]:
#lambda function

In [0]:
def square(x):
    print(x**2)

In [0]:
square(100)

10000


In [0]:
square(10) #custom function

100


In [0]:
np.square(10) #builtin function

100

In [0]:
# Anonymous function

In [0]:
model = lambda x: x**2 + x*3 - x

In [0]:
model(5)

35

In [0]:
model(10)

120

In [0]:
np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]], dtype=bool)

In [0]:
np.fromfunction(lambda i, j: i + j*10, (3, 3), dtype=int)

array([[ 0, 10, 20],
       [ 1, 11, 21],
       [ 2, 12, 22]])

In [0]:
iterable = (x*(x-1) for x in range(8))
np.fromiter(iterable, float)

array([  0.,   0.,   2.,   6.,  12.,  20.,  30.,  42.])

In [0]:
import os

In [0]:
os.getcwd()

'/Users/pradmishra/Documents'

In [0]:
np.fromfile('/Users/pradmishra/Documents/pg24407.txt')

array([  9.49270681e+077,   4.27186921e+034,   2.04909202e+190, ...,
         3.48319740e+228,   1.33452242e+179,   2.96551829e-260])

In [0]:
from io import StringIO

In [0]:
d = StringIO('# Convert each value according to its column and store')

In [0]:
np.loadtxt(d)

/Applications/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: loadtxt: Empty input file: "<_io.StringIO object at 0x10a12b1f8>"
  """Entry point for launching an IPython kernel.


array([], dtype=float64)

In [0]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3],names='a,b,c')
r

rec.array([(1, 'a',  1.1), (2, 'dd',  2. ), (3, 'xyz',  3. ), (4, '12',  4. )], 
          dtype=[('a', '<i8'), ('b', '<U3'), ('c', '<f8')])

In [0]:
np.linspace(10,40,20)

array([ 10.        ,  11.57894737,  13.15789474,  14.73684211,
        16.31578947,  17.89473684,  19.47368421,  21.05263158,
        22.63157895,  24.21052632,  25.78947368,  27.36842105,
        28.94736842,  30.52631579,  32.10526316,  33.68421053,
        35.26315789,  36.84210526,  38.42105263,  40.        ])

In [0]:
np.arange(10,40)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [0]:
np.arange(10,40,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [0]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [0]:
A

array([[ 3, -2,  1],
       [ 2,  3, -5],
       [-5, -7,  3]])

In [0]:
F = A.flatten()

In [0]:
F

array([ 3, -2,  1,  2,  3, -5, -5, -7,  3])

In [0]:
F.reshape(3,3)

array([[ 3, -2,  1],
       [ 2,  3, -5],
       [-5, -7,  3]])

In [0]:
np.arange(10,40).reshape(5,6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [0]:
len(np.arange(10,40))

30

In [0]:
np.arange(10,40).reshape(6,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [0]:
np.arange(10,40).reshape(10,3)

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36],
       [37, 38, 39]])

In [0]:
np.arange(10,40).reshape(2,15)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [0]:
# max, min and location
print("Max of a:", A.min())
print("Max of b:", A.max())
print("Max of c location:", A.argmax())
print("Max of c location:", A.argmin())

Max of a: -7
Max of b: 3
Max of c location: 0
Max of c location: 7


In [0]:
A/10

array([[ 0.3, -0.2,  0.1],
       [ 0.2,  0.3, -0.5],
       [-0.5, -0.7,  0.3]])

In [0]:
A

array([[ 3, -2,  1],
       [ 2,  3, -5],
       [-5, -7,  3]])

In [0]:
A[0]

array([ 3, -2,  1])

In [0]:
A[0,2]

1

In [0]:
A[0][2]

1

In [0]:
A[:,0]

array([ 3,  2, -5])

In [0]:
A[:,:]

array([[ 3, -2,  1],
       [ 2,  3, -5],
       [-5, -7,  3]])

In [0]:
A[0:2,1:3]

array([[-2,  1],
       [ 3, -5]])

In [0]:
A[:,:-1]

array([[ 3, -2],
       [ 2,  3],
       [-5, -7]])